[package]
name = "bma1020-project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = { git = "https://github.com/nannou-org/nannou", version = "0.18.1" }
vek = "0.15"
itertools = "0.10"
